### ISSUE TITLE
Avatar is too small on hi-res screens

### ISSUE THREAD

**Issue by raij** [7yl4r/AvatarWallpaper#2]
My Samsung Galaxy S3 has a 1280x720 display and the avatar looks pretty tiny.   We should do our best to keep the size of the avatar the same across all phones, independent of screen resolution.  This should be possible using resolution-independent units (inches?).

**Comment by 7yl4r** [comment]
ah, yes. I expected this would come up since the image size is currently static. 

Should be a somewhat straightforward fix to scale it based on the display size; I'll get to work on it.

**Comment by 7yl4r** [comment]
Oh, I did not realize resolution-independent units were supported. I'll use that instead.

**Comment by 7yl4r** [comment]
I just pushed a new version that scales the images in a more clever way. I expect they will look very pixelated on a high res screen, but I can fix that later with higher quality exports. Can you verify that they now fill most of the screen?

**Comment by raij** [comment]
## Looks pretty good on my screen!

Andrew Raij, Ph.D.
Assistant Professor, Department of Electrical Engineering
Courtesy Assistant Professor, Department of Computer Science and Engineering
University of South Florida
E-mail: raij@usf.edu
Web: http://www.eng.usf.edu/~raij

**Comment by 7yl4r** [comment]
Glad to hear it!
