### ISSUE TITLE
No way to get back to initial setup screen after first run

### ISSUE THREAD

**Issue by raij** [7yl4r/AvatarWallpaper#33]
If something goes wrong during initial setup (like camera failure), I don't get another chance to take a picture, select picture from the gallery, provide a unique name, etc.

A button could be added to the settings dialog to restart initial setup.  Alternatively, everything in initial setup could be added into the current settings screen.

**Comment by 7yl4r** [comment]
actually, there is a way to do this. If you go to the wallpaper settings and then press the 'menu' button, you will see options for 'initial setup' and 'support'. 

It is a bit hidden, but maybe that is okay?
