### ISSUE TITLE
Avatar is sleeping at 5:30pm.

### ISSUE THREAD

**Issue by raij** [7yl4r/AvatarWallpaper#4]

**Comment by 7yl4r** [comment]
That's definitely not right, since right now it shouldn't be sleeping at all. For now, try changing the 'current animation' in the settings to reset the activity level... 

I suspect it is a default value I left in somewhere which is only relevant upon first run.

**Comment by 7yl4r** [comment]
Yes, this is what the avatar is set to upon first startup of the app. I think we should leave it this way because it will act as a way to help ensure that the phone is either set to 'active' or 'passive' on the first day and not left on the default by accident.
