### ISSUE TITLE
Background is rapidly cycling through the first frame of each animation

### ISSUE THREAD

**Issue by raij** [7yl4r/AvatarWallpaper#5]
It was fine for at least an hour, and then this started happening.  Maybe it has something to do with the change from one animation to the next.

**Comment by raij** [comment]
I just tried changing the animation in the settings and that didn't fix it.

**Comment by 7yl4r** [comment]
I'm really not sure what might cause this. Is it cycling through the 1st frame only (so you see what is essentially a static image), or is it the first 2 or 3 frames?

**Comment by raij** [comment]
Actually, it's not necessarily showing the first frame. It's cycling very quickly, so it's hard to tell, but it looks like it shows one frame from one animation, then immediately switches to another frame in another animation, over and over.

**Comment by 7yl4r** [comment]
I just pushed a new version in an attempt to fix this problem; please give it a try.

**Comment by raij** [comment]
Looks good so far.

The one issue is that the animation is playing a bit slower than before.  It's not bad, but it might be perceived as a performance issue.

-Andrew

---

Andrew Raij, Ph.D.
Assistant Professor, Department of Electrical Engineering
Courtesy Assistant Professor, Department of Computer Science and Engineering
University of South Florida
E-mail: raij@usf.edumailto:raij@usf.edu
Web: http://www.eng.usf.edu/~raij

On Aug 6, 2012, at 11:39 PM, Tylar <notifications@github.com<mailto:notifications@github.com>> wrote:

I just pushed a new version in an attempt to fix this problem; please give it a try.

**Comment by 7yl4r** [comment]
That is intentional. I turned the frame rate down to 7fps to help with debugging this issue and to see what effect frame rate might have on battery life. I'll turn it back up in the next version.
