### ISSUE TITLE
Images for background show up in photos

### ISSUE THREAD

**Issue by 7yl4r** [7yl4r/AvatarWallpaper#8]
When looking through the phone gallery the images show up, allowing users to easily (accidentally) delete or modify them, resulting in a broken wallpaper.

I believe that a restart of the wallpaper will fix it, but ideally, I think these images ought to be a bit more hidden from the user.

**Comment by 7yl4r** [comment]
this can be resolved by making the MirrorMe/sprites/ directory hidden (MirrorMe/.sprites/) or by using the [internal storage](http://developer.android.com/guide/topics/data/data-storage.html#filesInternal) for these instead.

edit: internal storage is not an option so long as the AvatarCustomize app is separate, since an app's internal storage is private.

**Comment by 7yl4r** [comment]
Alternatively, the bitmaps can be saved with an obfuscated file extension, which is then chopped off and replaced with the real extension to retrieve the bitmap.

**Comment by 7yl4r** [comment]
the images themselves have been made hidden files using the '.' prefix.

**Comment by 7yl4r** [comment]
apparently making them unix hidden files (using the '.') does not prevent them from being picked up in the gallery.

**Comment by raij** [comment]
Have you tried any of the ideas posted at the url below:

http://www.addictivetips.com/mobile/how-to-prevent-a-directory-from-being-scanned-by-android-gallery/

**Comment by 7yl4r** [comment]
I have not seen the .nomedia trick before. That will likely be a very easy solution. I'll give it a shot.

**Comment by 7yl4r** [comment]
I finally got everything on my test phone figured out enough that I can verify that this is fixed for sure this time. Doing complete re-installs without a method to remove files on uninstall automatically is no fun.
